/**
 * Canonical language list for the order-request form. Values are sent to
 * the order-requests API verbatim and must match this list exactly — no
 * localization, the option label is always the canonical English name.
 * The most requested languages for a Lutsk-based agency are pinned to the
 * top; the rest follow alphabetically.
 */
export const languages = [
  "English",
  "Ukrainian",
  "Polish",
  "German",
  "Dutch",
  "Bulgarian",
  "Afrikaans",
  "Albanian",
  "Arabic",
  "Armenian",
  "Azerbaijani",
  "Belarusian",
  "Bosnian",
  "Chinese",
  "Croatian",
  "Czech",
  "Danish",
  "Estonian",
  "Finnish",
  "French",
  "Georgian",
  "Greek",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Italian",
  "Japanese",
  "Kazakh",
  "Korean",
  "Kyrgyz",
  "Latin",
  "Latvian",
  "Lithuanian",
  "Macedonian",
  "Malay",
  "Montenegrin",
  "Norwegian",
  "Persian",
  "Portuguese",
  "Romanian",
  "Russian",
  "Serbian",
  "Slovak",
  "Slovenian",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tajik",
  "Thai",
  "Turkish",
  "Turkmen",
  "Urdu",
  "Uzbek",
  "Vietnamese",
] as const;

export type Language = (typeof languages)[number];
